# Generated by Django 4.2 on 2023-06-23 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.centre')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_abonnement', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.centre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='centre',
            name='abonnements',
            field=models.ManyToManyField(related_name='centres', to='Backend.abonnement'),
        ),
        migrations.AddField(
            model_name='centre',
            name='messages',
            field=models.ManyToManyField(related_name='centres', to='Backend.message'),
        ),
    ]
